name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    permissions:
      contents: read 
      security-events: write
      actions: read 
    name: Build
    runs-on: "ubuntu-18.04"
    steps:
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v1
        with:
          image-ref: docker.io/library/nginx:1.20.2
          severity: 'CRITICAL,HIGH'
          output: html
          id: trivy-scan
    
      - name: Upload Trivy HTML report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: trivy-report
          path: trivy-report.html
